### ISSUE TITLE
Failed to find <file> from <path>

### ISSUE THREAD

**Issue by iamvdo** [postcss/postcss-import#14]
This error occurs multiple times, and I don't understand real issue here.

First, your README example doesn't work. If I use `from` option, I get:

```javascript
TypeError: Property '0' of object [object Object],function AtImport(options) {
  // blah blah blah
} is not a function
```

If I don't use the `from` option, I get the `Failed to find <file> from <path>` error.

If I use the `path` option, it used to work with 3.2.0 version, but no longer work with 4.0.0. Still the `Failed to find <file> from <path>` error.

Any thought ?
